# Generated by Django 4.2.27 on 2026-04-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_application_description"),
        ("academicsection", "0013_coursebatch_faculty"),
        ("faculty", "0002_faculty_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssessmentComponent",
            fields=[
                ("component_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "component_type",
                    models.CharField(default="assignment", max_length=30),
                ),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="academicsection.branchbatch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="academicsection.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["component_id"],
                "unique_together": {("batch", "course", "title")},
            },
        ),
        migrations.CreateModel(
            name="CourseScoresheetSubmission",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_components", models.PositiveIntegerField(default=0)),
                (
                    "total_max_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "average_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoresheet_submissions",
                        to="academicsection.branchbatch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoresheet_submissions",
                        to="academicsection.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoresheet_submissions",
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAssessmentScore",
            fields=[
                ("score_id", models.AutoField(primary_key=True, serialize=False)),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="faculty.courseassessmentcomponent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_scores",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("component", "student")},
            },
        ),
    ]
