"""
URL configuration for backend project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from .views import (
    add_admin_api,
    create_department_api,
    create_department_course_api,
    create_department_faculty_api,
    create_branch_batch_api,
    create_branch_api,
    change_password_api,
    create_user_api,
    delete_admin_api,
    delete_managed_user_api,
    faculty_options_api,
    get_branch_batch_detail_api,
    get_department_detail_api,
    get_departments_branches_api,
    get_timetable_api,
    get_managed_user_detail_api,
    list_admins_api,
    list_departments_api,
    list_branch_batches_api,
    list_managed_users_api,
    login_api,
    delete_branch_batch_api,
    reset_admin_password_api,
    save_timetable_api,
    update_admin_api,
    update_managed_user_api,
    update_branch_api,
    update_branch_batch_api,
    update_department_api,
    assign_course_to_batch_api,
    unassign_course_from_batch_api,
    get_courses_for_batch_api,
    get_student_my_courses_api,
    get_students_in_batch_api,
    get_students_in_course_api,
    get_faculty_courses_api,
    get_faculty_profile_api,
    get_faculty_timetable_api,
    get_faculty_course_students_api,
    get_faculty_course_marks_api,
    get_faculty_attendance_students_api,
    save_faculty_attendance_api,
    save_faculty_course_marks_api,
    submit_faculty_scoresheet_api,
    get_student_current_semester_attendance_api,
    raise_missed_class_attendance_query_api,
    get_student_results_api,
)
from app_apis import (
    list_applications_api,
    get_application_detail_api,
    send_application_api,
    respond_to_application_api,
    delete_application_api,
    get_users_for_recipients_api,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/login/', login_api, name='login_api'),
    path('api/change-password/', change_password_api, name='change_password_api'),
    path('api/admin/create-user/', create_user_api, name='create_user_api'),
    path('api/admin/departments/', list_departments_api, name='list_departments_api'),
    path('api/admin/departments/<int:department_id>/', get_department_detail_api, name='get_department_detail_api'),
    path('api/admin/departments/create/', create_department_api, name='create_department_api'),
    path('api/admin/departments/faculty/create/', create_department_faculty_api, name='create_department_faculty_api'),
    path('api/admin/departments/courses/create/', create_department_course_api, name='create_department_course_api'),
    path('api/admin/departments/update/', update_department_api, name='update_department_api'),
    path('api/admin/branches/create/', create_branch_api, name='create_branch_api'),
    path('api/admin/branches/update/', update_branch_api, name='update_branch_api'),
    path('api/admin/branches/batches/create/', create_branch_batch_api, name='create_branch_batch_api'),
    path('api/admin/branches/batches/update/', update_branch_batch_api, name='update_branch_batch_api'),
    path('api/admin/branches/batches/delete/', delete_branch_batch_api, name='delete_branch_batch_api'),
    path('api/admin/branch-batches/', list_branch_batches_api, name='list_branch_batches_api'),
    path('api/admin/branch-batches/<int:batch_id>/', get_branch_batch_detail_api, name='get_branch_batch_detail_api'),
    path('api/admin/faculty-options/', faculty_options_api, name='faculty_options_api'),
    path('api/admin/departments-branches/', get_departments_branches_api, name='get_departments_branches_api'),
    path('api/admin/manage-users/', list_managed_users_api, name='list_managed_users_api'),
    path('api/admin/manage-users/detail/', get_managed_user_detail_api, name='get_managed_user_detail_api'),
    path('api/admin/manage-users/update/', update_managed_user_api, name='update_managed_user_api'),
    path('api/admin/manage-users/delete/', delete_managed_user_api, name='delete_managed_user_api'),
    path('api/timetable/', get_timetable_api, name='get_timetable_api'),
    path('api/timetable/save/', save_timetable_api, name='save_timetable_api'),
    path('api/admin/courses/batch/assign/', assign_course_to_batch_api, name='assign_course_to_batch_api'),
    path('api/admin/courses/batch/unassign/', unassign_course_from_batch_api, name='unassign_course_from_batch_api'),
    path('api/admin/batches/<int:batch_id>/courses/', get_courses_for_batch_api, name='get_courses_for_batch_api'),
    path('api/admin/batches/students/', get_students_in_batch_api, name='get_students_in_batch_api'),
    path('api/admin/courses/students/', get_students_in_course_api, name='get_students_in_course_api'),
    path('api/student/my-courses/', get_student_my_courses_api, name='get_student_my_courses_api'),
    path('api/faculty/my-courses/', get_faculty_courses_api, name='get_faculty_courses_api'),
    path('api/faculty/timetable/', get_faculty_timetable_api, name='get_faculty_timetable_api'),
    path('api/faculty/profile/', get_faculty_profile_api, name='get_faculty_profile_api'),
    path('api/faculty/course-students/', get_faculty_course_students_api, name='get_faculty_course_students_api'),
    path('api/faculty/course-marks/', get_faculty_course_marks_api, name='get_faculty_course_marks_api'),
    path('api/faculty/attendance/students/', get_faculty_attendance_students_api, name='get_faculty_attendance_students_api'),
    path('api/faculty/attendance/save/', save_faculty_attendance_api, name='save_faculty_attendance_api'),
    path('api/faculty/course-marks/save/', save_faculty_course_marks_api, name='save_faculty_course_marks_api'),
    path('api/faculty/course-marks/submit-scoresheet/', submit_faculty_scoresheet_api, name='submit_faculty_scoresheet_api'),
    path('api/student/current-semester-attendance/', get_student_current_semester_attendance_api, name='get_student_current_semester_attendance_api'),
    path('api/student/attendance/raise-query/', raise_missed_class_attendance_query_api, name='raise_missed_class_attendance_query_api'),
    path('api/student/results/', get_student_results_api, name='get_student_results_api'),
    path('api/admin/admins/add/', add_admin_api, name='add_admin_api'),
    path('api/admin/admins/list/', list_admins_api, name='list_admins_api'),
    path('api/admin/admins/delete/', delete_admin_api, name='delete_admin_api'),
    path('api/admin/admins/reset-password/', reset_admin_password_api, name='reset_admin_password_api'),
    path('api/admin/admins/update/', update_admin_api, name='update_admin_api'),
    path('api/admin/applications/', list_applications_api, name='list_applications_api'),
    path('api/admin/applications/detail/', get_application_detail_api, name='get_application_detail_api'),
    path('api/admin/applications/send/', send_application_api, name='send_application_api'),
    path('api/admin/applications/respond/', respond_to_application_api, name='respond_to_application_api'),
    path('api/admin/applications/delete/', delete_application_api, name='delete_application_api'),
    path('api/admin/recipients/', get_users_for_recipients_api, name='get_users_for_recipients_api'),
    path('api/applications/', list_applications_api, name='shared_list_applications_api'),
    path('api/applications/detail/', get_application_detail_api, name='shared_get_application_detail_api'),
    path('api/applications/send/', send_application_api, name='shared_send_application_api'),
    path('api/applications/respond/', respond_to_application_api, name='shared_respond_to_application_api'),
    path('api/applications/delete/', delete_application_api, name='shared_delete_application_api'),
    path('api/applications/recipients/', get_users_for_recipients_api, name='shared_get_users_for_recipients_api'),
]
