# Generated by Django 5.2.6 on 2026-02-10 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('familyincome', models.CharField(max_length=10)),
                ('abcid', models.CharField(max_length=12)),
                ('cgpa', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('acno', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=11)),
                ('branchname', models.CharField(max_length=20)),
                ('branchaddress', models.CharField(max_length=100)),
                ('rollno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
