# Generated by Django 4.2.27 on 2026-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminApplication",
            fields=[
                ("app_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=200)),
                ("sender_type", models.CharField(max_length=20)),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_email", models.CharField(max_length=100)),
                ("receiver_type", models.CharField(max_length=20)),
                ("receiver_email", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
