# Generated by Django 4.2.27 on 2026-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_adminapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
