# Generated by Django 5.2.6 on 2026-02-10 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicsection', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='monday',
            name='branch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academicsection.branch'),
        ),
        migrations.AddField(
            model_name='monday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course'),
        ),
        migrations.AddField(
            model_name='monday',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='saturday',
            name='branch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academicsection.branch'),
        ),
        migrations.AddField(
            model_name='saturday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course'),
        ),
        migrations.AddField(
            model_name='saturday',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='thursday',
            name='branch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academicsection.branch'),
        ),
        migrations.AddField(
            model_name='thursday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course'),
        ),
        migrations.AddField(
            model_name='thursday',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='branch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academicsection.branch'),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course'),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='branch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academicsection.branch'),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course'),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='friday',
            unique_together={('branch_id', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='monday',
            unique_together={('branch_id', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='saturday',
            unique_together={('branch_id', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='thursday',
            unique_together={('branch_id', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='tuesday',
            unique_together={('branch_id', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='wednesday',
            unique_together={('branch_id', 'time_slot')},
        ),
    ]
