# Generated by Django 5.2.6 on 2026-04-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicsection', '0006_branchbatch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='academicsec_role_506fa9_idx',
            old_name='academicsec_role_c4f2af_idx',
        ),
    ]
