# Generated by Django 5.2.6 on 2026-04-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicsection', '0007_rename_academicsec_role_c4f2af_idx_academicsec_role_506fa9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchbatch',
            name='college_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
