# Generated by Django 5.2.6 on 2026-04-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicsection', '0008_branchbatch_college_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='college_years',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
