# Generated by Django 6.0.4 on 2026-04-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicsection', '0010_userprofile_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academicsection.branchbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicsection.course')),
            ],
            options={
                'unique_together': {('batch', 'course')},
            },
        ),
    ]
